### ISSUE TITLE
Typings is incorrect

### ISSUE THREAD

**Issue by etienne-dldc** [toish/chromatism#15]
Hi,

The module is typed as exporting all function while it's a default import.

So `import { brightness } from 'chromatism'` or `import * as chromatism from 'chromatism'` does not throw typing error but does not work (`chromatism_1.brightness is not a function`).
But `import chromatism from 'chromatism'` does not pass type checking : `error TS1192: Module '"~/node_modules/chromatism/index"' has no default export.`

The following `index.d.ts`should fix this : 
```ts
declare namespace Chromatism {
     // All the code of the old `index.d.ts`
}

export default Chromatism;
```

Etienne.

**Comment by toish** [comment]
Currently on holiday in the UK with some pretty spotty wifi, thanks for your suggestion, but I won't be able to fix this up before I get back! Thanks so much again!

**Comment by etienne-dldc** [comment]
I can do a PR if you want ☺️

**Comment by toish** [comment]
Yes please if you can! I'm back on the 21st-22nd, should be able to merge your stuff in then or fix stuff up myself! Thanks so much again!

**Comment by TehShrike** [comment]
Worth noting that it's probably best to update the typings in the `refactor` branch, where there are breaking API changes that should be merged/released in the next couple weeks.

**Comment by toish** [comment]
Not needed now that we're using ES6 named exports
