### ISSUE TITLE
`adapt()` should take a illuminant name, rather than a colour.

### ISSUE THREAD

**Issue by toish** [toish/chromatism#19]
This saves us having to put a constants object into the final export, and instead just refer to the CIE standard illuminants by their name. (`"D65"`, `"F2"`, etc)

**Comment by toish** [comment]
This is set up now, using the illuminant label, or, if the illuminant doesn't exists, defaulting to `D65`. This may need to throw an error in the future, because I don't really like the idea of things failing silently.

**Comment by TehShrike** [comment]
I support throwing an error on invalid input 👍
