### ISSUE TITLE
Update readme with the refactor branch API changes

### ISSUE THREAD

**Issue by TehShrike** [toish/chromatism#21]
Should include both the upcoming changes to `adapt` (#19) and the fact that chaining is no longer supported.

I think that's the only API changes?

It would be good to note that ES modules/treeshaking is supported, for the browser-serving folks like me who are toolbox-module-averse.

Not as important, but we should also consider adding some really small example lines for each function for people to see and copy/paste.  We can use [jsmd](https://www.npmjs.com/package/jsmd) to make sure that the examples stay accurate.

**Comment by toish** [comment]
Love the idea of using hand for this. I also have been on-and-off working on a demo for each one of the methods. Might get something online we can link to for each operation

**Comment by toish** [comment]
Sorry for the wait! See #28 !

**Comment by toish** [comment]
Fixed in #28
