### ISSUE TITLE
Eliminate HSV->RGB or HSL->RGB conversion

### ISSUE THREAD

**Issue by TehShrike** [toish/chromatism#25]
HSV and HSL are very similar, and those conversions take a lot of code, so it's better not to keep both versions around.

Context: https://github.com/toish/chromatism/pull/24

When I tried removing either of the conversions, the output values changed enough that the tests wouldn't pass.

This implies that the conversions might be lossier than they should be, or one of them is less accurate than it should be.

**Comment by toish** [comment]
Fixed in #26
