### ISSUE TITLE
Need to include CJS bundle in repo so this package can continue to work in CDNjs

### ISSUE THREAD

**Issue by toish** [toish/chromatism#27]
Chromatism got included in CDNjs, and I don't wanna break the package when used thru it in the browser! Thinking we should un-gitignore `/dist`?

**Comment by TehShrike** [comment]
CDNjs uses Github instead of npm?

**Comment by toish** [comment]
It won't run a build task AFAIK, so I'm thinking we need to have a browser-compatible build already in the package

**Comment by TehShrike** [comment]
It doesn't look like CDNjs would require anything in this repo - it would only require that we open pull requests to their repo to add the built/minified file.

I like unpkg because it doesn't require me to do anything besides push to npm ;-) https://unpkg.com/chromatism

**Comment by toish** [comment]
PR #29 adds the `/dist` directory to the NPM packages, which contains a UMD module
