### ISSUE TITLE
want use @3.02

### ISSUE THREAD

**Issue by edenYfb** [toish/chromatism#41]
'package.json'  version is 3.0.0, i want use @3.0.2, but how to install it?

**Comment by edenYfb** [comment]
chromatism.convert({  h:0, s:0, l:0 }).hsv==>{h:0,s:nan,v:0}
chromatism.convert({  r:0, g:0, b:0 }).hsv==>{h:0,s:nan,v:0}

**Comment by TehShrike** [comment]
Are you talking about [this version](https://www.npmjs.com/package/chromatism2)?

**Comment by edenYfb** [comment]
haha,thank you
