### ISSUE TITLE
hsl-->rgb，error is a little big

### ISSUE THREAD

**Issue by edenYfb** [toish/chromatism#43]
chromatism.convert( { h: 300, s: 100, l: 50 } ).rgb
//-->{r:253.47, g:0, b:254.49}-->Math.round()-->253,0,254
i want  it can be {r:255, g:0, b:255},  after Math.round()

**Comment by TehShrike** [comment]
Then write a round function that does that.  [`Math.round`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) does not work that way.

**Comment by edenYfb** [comment]
ok, i try it
