### ISSUE TITLE
HSLuv color space support

### ISSUE THREAD

**Issue by epiloque** [toish/chromatism#5]
[HSLuv](https://github.com/hsluv/hsluv/) is a human-friendly alternative to HSL. 

--

chromatism is awesome, thank you!

**Comment by toish** [comment]
Hey thanks for the suggestion!
I'll need to implement CIE L*u*v* and it's cylindrical counterpart before I can implement HSLuv. Been putting off adding more CIE colour models as they aren't as useful for colour functions, but HSLuv seems really interesting! I've added CIE LUV to the roadmap, next will be HSLuv https://github.com/toish/chromatism/projects/2#card-3138870

**Comment by iondrimba** [comment]
@toish you are very responsive to Issues and PR´s, hats off on that!

**Comment by toish** [comment]
@epiloque I've implemented L\*u\*v\*, should be able to get Lch set up tomorrow along with HSLuv/HPLuv

@iondrimba Thanks! I'm honestly just excited that this many people seem to be interested in the math behind colour!

**Comment by epiloque** [comment]
@toish that's great! Thank you very much. Can I help somehow? ES6 / rollup configuration …

**Comment by toish** [comment]
@epiloque Would love some help with tweaking the rollup config/getting the ES6 module to be tree-shakable! Will also be working on adding to the chain of colour modes I need to get to HSLuv tonight if you'd like to help!

**Comment by toish** [comment]
@epiloque Added support for HSLuv!
